### ISSUE TITLE
Add setup (docker) and enable ssh testing

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#19]
Should be done within https://github.com/datalad/datalad-extensions/blob/master/.github/workflows/build-git-annex-debianstandalone.yaml only for now, until #18 is merged.

@kyleam, help?!

**Comment by kyleam** [comment]
Sure.  Most of the pieces for a docker ssh target are in place in the scratch/docker-ssh in the datalad repo.  As I mentioned on the call today, I'd still like to adopt that (at least as an option), though it got put on the back burner because it didn't actually resolve any of the Travis hangs.

I can revisit that and try to pull out common parts for use here (including putting an image somewhere on dockerhub), though perhaps there will be github ci hurdles in adopting that setup here.  Even with an image hosted, I think a wrapper Dockerfile and `docker build` call may still be needed for the uid handling.

**Comment by yarikoptic** [comment]
Sounds like a plan!  Since it didn't resolve hanging -- that is great -- it reproduced it, so we could be sure for docker setup to be as good ;) 

FWIW, in this repo, I am planing to start using tools from https://github.com/datalad/datalad/tree/master/tools/ci (e.g. absorb https://github.com/datalad/datalad-extensions/blob/master/scripts/ci/download-latest-artifact (from #18 which I just merged) into https://github.com/datalad/datalad/pull/4640/files#diff-310e23a98b20f6aa856982181d5f4fa6 . So adding docker setup within https://github.com/datalad/datalad/tree/master/tools/ci  and making it available here as well would align!
